Credit notes
Fimento/api-documentation pull request #18
Opened 2023-02-07 15:38 UTC by Erik-Nilsson-Fimento

2023-02-07 16:01 UTC, DavidVergnaultMoank requested changes

2023-02-07 16:01 UTC, DavidVergnaultMoank commented on specifications.yml
> +  /order/{orderId}/credit-note:
/return

2023-02-07 16:01 UTC, DavidVergnaultMoank commented on specifications.yml
> +          $ref: "#/components/responses/creditNoteSuccess"
createReturnSuccess

2023-02-07 16:01 UTC, DavidVergnaultMoank commented on specifications.yml
> +      summary: Create a return
We need to be more explicit I feel here

2023-02-07 16:01 UTC, DavidVergnaultMoank commented on specifications.yml
> +      description: Items to return
Not only the items, we need a date as well perhaps and other informations like a comment etc ?

2023-02-07 16:01 UTC, DavidVergnaultMoank commented on specifications.yml
> +              orderId:
you forgot something after `orderId` :thinking: 
We should return a specific id about the return as well. It can be a transaction id or whatever else but they need to be able to track it in their system

2023-02-07 16:01 UTC, DavidVergnaultMoank commented on specifications.yml
> +                description: Article description
No need

2023-02-13 10:52 UTC, Erik-Nilsson-Fimento commented on specifications.yml
> +                description: Article description
Its required though  :thinking:

2023-02-13 12:49 UTC, DavidVergnaultMoank approved these changes, later dismissed

2023-02-13 15:42 UTC, DavidVergnaultMoank requested changes

2023-02-13 15:42 UTC, DavidVergnaultMoank commented on specifications.yml
> +    instalmentPaymentMethod:
Not used anymore

2023-02-14 09:15 UTC, merged